spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: callme-service
          uri: http://localhost:8040
          predicates:
            - Path=/callme/**
        - id: caller-service
          uri: http://localhost:8020
          predicates:
            - Path=/caller/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/demo/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/demo
        registration:
          spring-with-test-scope:
            provider: keycloak
            client-id: spring-with-test-scope
            client-secret: IWLSnakHG8aNTWNaWuSj0a11UY4lzxd9
            authorization-grant-type: authorization_code
            scope: openid
#          keycloak-without-test-scope:
#            provider: keycloak
#            client-id: spring-without-test-scope
#            client-secret: f6fc369d-49ce-4132-8282-5b5d413eba23
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/spring-without-test-scope"

server.port: 8060

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE